#!/bin/bash

set -x
set -e

mkdir --parents ./mediawiki

for file in ./*; do

   if [ "$file" = "$0" ]; then
      continue
   fi
   
   if [ -d "$file" ]; then
      continue
   fi

   filename="$(basename "$file")"

   pandoc -r markdown -w mediawiki -o ./mediawiki/"$filename" "$file"

done

